#
# Data Container Dockerfile
#
#

# Pull base image.
FROM dockerfile/ubuntu

# Define mountable directories.
# Dev
VOLUME ["/home"]
# Apache
VOLUME ["/app", "/var/log/apache2"]

# Define default command.
CMD ["true"]
